blank_issues_enabled: false
contact_links:
- name: Bug Report
url: https://github.com/KayleighOwO/VSCodeReBeautify/issues/new?template=bug_report.md
about: Report a bug to help us improve.
- name: Feature Request
url: https://github.com/KayleighOwO/VSCodeReBeautify/issues/new?template=feature_request.md
about: Suggest a new feature for the project.
